language: rust
rust:
  - stable
matrix:
  allow_failures:
    - rust: nightly
cache: cargo

before_script:
  - wget https://github.com/Keats/gutenberg/releases/download/v0.3.1/gutenberg-v0.3.1-x86_64-unknown-linux-gnu.tar.gz -O /tmp/gutenberg.tar.gz
  - tar -xvf /tmp/gutenberg.tar.gz
  - wget https://github.com/netlify/netlifyctl/releases/download/v0.3.1/netlifyctl-linux-amd64-0.3.1.tar.gz -O /tmp/netlifyctl.tar.gz
  - tar -xvf /tmp/netlifyctl.tar.gz
  - export PATH=$PATH:$PWD/

script:
  - cargo test --verbose --release
  - cargo run redirects.toml --release
  - cd website
  - mkdir themes/gutenberg-rustref/static themes/gutenberg-rustref/sass
  - gutenberg build
  - cp ../_redirects public/
  - echo "/home /" >> public/_redirects
  - echo "http://test.rustref.com/* http://nocduro.com/:splat 301!" >> public/_redirects
  - echo "https://test.rustref.com/* http://nocduro.com/:splat 301!" >> public/_redirects
  - echo "http://hello.rustref.com/* http://nocduro.com/ 301!" >> public/_redirects
  - cat public/_redirects

after_success:
  - echo $PWD
  - ls
  - ls public
  - netlifyctl deploy -s $NETLIFY_SITE_ID -A $NETLIFY_TOKEN -b public