language: rust
rust:
  - stable
matrix:
  allow_failures:
    - rust: nightly
cache: cargo

before_script:
  - wget https://github.com/Keats/gutenberg/releases/download/v0.3.1/gutenberg-v0.3.1-x86_64-unknown-linux-gnu.tar.gz -O /tmp/gutenberg.tar.gz
  - tar -xvf /tmp/gutenberg.tar.gz
  - export PATH=$PATH:$PWD/

script:
  - cargo test --verbose --release
  - cargo run redirects.toml --release
  - cd website
  - mkdir themes/gutenberg-rustref/static themes/gutenberg-rustref/sass
  - gutenberg build
  - cp ../_redirects public/

after_success:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git checkout -b rendered
  - git add .
  - git commit --message "Travis build ${TRAVIS_BUILD_NUMBER}"
  - git remote add origin-pages https://${GH_TOKEN}@github.com/nocduro/rustref.git > /dev/null 2>&1
  - git push --quiet --force --set-upstream origin-pages rendered
