[package]
name = "rustref"
version = "0.1.0"
authors = ["Mackenzie Hauck <mhauck@live.ca>"]

[dependencies]
rayon = "1.0"
reqwest = "0.8"
serde = "1.0"
serde_derive = "1.0" 
toml = "0.4"
url = "1.6"
serde_json = "1.0"